baseURL = 'https://arc-community.in/'
locale = 'en-us'
title = 'Ambedkar Reading Circle'
disableKinds = ['page', 'section', 'taxonomy', 'term']

ignoreLogs = ['warning-goldmark-raw-html']

[params]
  description = "A people's collective to occupy public spaces and public imagination with anti-caste literature, iconographies, thought, and imagination."
  status = "under construction"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
